name: Test Scala CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11.0-11
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Run tests
      run: sbt +test

  merge:
    name: Merge dependency update
    if: github.actor == 'some-bot'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: merge PR
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          ALLOWED_UPDATE: minor
          MERGE_METHOD: rebase